### ISSUE TITLE
No rails dataset running with nginx and passenger

### ISSUE THREAD

**Issue by Sergio-Mira** [honeycombio/honeycomb-rails#22] opened 2018-07-27 14:44 UTC
When running with nginx and passenger we get data for the active_record dataset but not the rails controller/action data.
Running the same Rails app using thin makes both data sets appear in Honeycomb right away.

Looking at the code I can't see how this could have any effect on the extensions that should be triggering in the lib and I feel like a madman just asking, have you heard of any similar problems before? How can the active_record data be sent and not the rails controller events?

Thanks!

**Comment by samstokes** [comment] 2018-07-27 17:30
Hi Sergio! That does sound surprising, although I don't think we've tested in Passenger yet. Would I be right in guessing that Passenger is your production config and so this is preventing you from trying out honeycomb-rails in production?

I can have a go at reproducing - could you give me a bit more information on your setup, in case any of it is relevant?
 * OS and version
 * nginx version
 * passenger version
 * Ruby version
 * Rails version

Also would you mind pasting your HoneycombRails config (e.g. the contents of `config/initializers/honeycomb.rb`) so I can double-check that? Please don't paste your write key here though :)

If for any reason you'd prefer not to put any of this info in a public Github Issue, please feel free to email it to support@honeycomb.io and we can help you out there as well.

**Comment by Sergio-Mira** [comment] 2018-07-31 16:46
I've spent some time instrumenting the gem with logs and as soon as the first event from a controller is added to the queue the loops stop working (ProcessAction then TransmissionClient.add), no Exception nor ThreadError.

>>> ## TransmissionClient queue added
## TransmissionClient starting synchronize
## Thread count 10 at max 10
## THEAD INFO [#<Thread:0x0000000be25850@/var/lib/gems/2.2.0/gems/logging-2.1.0/lib/logging/diagnostic_context.rb:447 dead>, #<Thread:0x0000000be25670@/var/lib/gems/2.2.0/gems/logging-2.1.0/lib/logging/diagnostic_context.rb:447 dead>, #<Thread:0x0000000be25300@/var/lib/gems/2.2.0/gems/logging-2.1.0/lib/logging/diagnostic_context.rb:447 dead>, #<Thread:0x0000000be25120@/var/lib/gems/2.2.0/gems/logging-2.1.0/lib/logging/diagnostic_context.rb:447 dead>, #<Thread:0x0000000be24db0@/var/lib/gems/2.2.0/gems/logging-2.1.0/lib/logging/diagnostic_context.rb:447 dead>, #<Thread:0x0000000be24b80@/var/lib/gems/2.2.0/gems/logging-2.1.0/lib/logging/diagnostic_context.rb:447 dead>, #<Thread:0x0000000be248b0@/var/lib/gems/2.2.0/gems/logging-2.1.0/lib/logging/diagnostic_context.rb:447 dead>, #<Thread:0x0000000be24680@/var/lib/gems/2.2.0/gems/logging-2.1.0/lib/logging/diagnostic_context.rb:447 dead>, #<Thread:0x0000000be24478@/var/lib/gems/2.2.0/gems/logging-2.1.0/lib/logging/diagnostic_context.rb:447 dead>, #<Thread:0x0000000be241f8@/var/lib/gems/2.2.0/gems/logging-2.1.0/lib/logging/diagnostic_context.rb:447 dead>]

All theads are reported as dead as soon as a controller action happens. Before that they were `sleep` except one that is `run`:
>>> ## THEAD INFO [#<Thread:0x0000000be25850@/var/lib/gems/2.2.0/gems/logging-2.1.0/lib/logging/diagnostic_context.rb:447 sleep>, #<Thread:0x0000000be25670@/var/lib/gems/2.2.0/gems/logging-2.1.0/lib/logging/diagnostic_context.rb:447 sleep>, #<Thread:0x0000000be25300@/var/lib/gems/2.2.0/gems/logging-2.1.0/lib/logging/diagnostic_context.rb:447 sleep>, #<Thread:0x0000000be25120@/var/lib/gems/2.2.0/gems/logging-2.1.0/lib/logging/diagnostic_context.rb:447 run>, #<Thread:0x0000000be24db0@/var/lib/gems/2.2.0/gems/logging-2.1.0/lib/logging/diagnostic_context.rb:447 sleep>, #<Thread:0x0000000be24b80@/var/lib/gems/2.2.0/gems/logging-2.1.0/lib/logging/diagnostic_context.rb:447 sleep>, #<Thread:0x0000000be248b0@/var/lib/gems/2.2.0/gems/logging-2.1.0/lib/logging/diagnostic_context.rb:447 sleep>, #<Thread:0x0000000be24680@/var/lib/gems/2.2.0/gems/logging-2.1.0/lib/logging/diagnostic_context.rb:447 sleep>, #<Thread:0x0000000be24478@/var/lib/gems/2.2.0/gems/logging-2.1.0/lib/logging/diagnostic_context.rb:447 sleep>, #<Thread:0x0000000be241f8@/var/lib/gems/2.2.0/gems/logging-2.1.0/lib/logging/diagnostic_context.rb:447 sleep>]

Any idea why those would die when a ProcessAction is triggered?

**Comment by Sergio-Mira** [comment] 2018-07-31 17:01
Ruby: `ruby 2.2.8p477`
Rails: `4.2.7.1`
nginx: `nginx/1.12.1`
passenger: `Phusion Passenger 5.1.11`
honeycomb initializer:
```
HoneycombRails.configure do |conf|
    conf.writekey = CONFIG.honeycomb.write_key
    conf.dataset = CONFIG.honeycomb.dataset_name
    conf.db_dataset = CONFIG.honeycomb.db_dataset_name
    conf.record_user = false
  end
```

**Comment by Sergio-Mira** [comment] 2018-08-13 09:55
I've been trying to find out what is going on and it all points to issues when doing .pop in the sizedqueue, but surprisingly no being/rescue is triggered and the thread doesn't contain any info when it dies. Tried changing to a `Queue` and still get the same result. It doesn't seem important the number of threads (reduced to 1), the data enqueued or that I disable the controller action events.

Have you ever had someone with issues with SizedQueue before?

**Comment by Sergio-Mira** [comment] 2018-08-16 10:28
Any ideas? Could it similar to the issues another team is seeing here https://github.com/CaseyLeask/honeycomb-rails/pull/1/commits/bde3dfa05de133005ffdcb6bf3da4154f1704a5c ?

**Comment by samstokes** [comment] 2018-08-17 02:03
Hi @Sergio-Mira, sorry for not getting back to you sooner about this. Thanks for doing some investigation yourself as well! Unfortunately I'm having trouble reproducing this issue :(

Is there any chance you could post or email your `Gemfile.lock` as well, so I can see which versions of various libraries your app is running?

I've not heard of issues with SizedQueue before - it was only added in Ruby 2.2 but you're running on that version so it should be fine.

**Comment by Sergio-Mira** [comment] 2018-09-07 16:40
Using the version https://github.com/CaseyLeask/honeycomb-rails seems to solve our issues. I've sent an email with our Gemfile.lock before changing to the fork. Thanks!

**Comment by samstokes** [comment] 2018-09-13 17:29
Hi @Sergio-Mira, really sorry for not responding sooner, and thanks for sending over your Gemfile.lock! I've been trying to reproduce this issue but with no luck - this is a classic "should not be happening" kind of bug :(

We did just put out a new release of libhoney (which as you've discovered is used by honeycomb-rails under the hood) that may mitigate this issue - any chance you could try a `bundle update libhoney` and seeing if that makes any difference? You can confirm you're on the new version by running `grep libhoney Gemfile.lock` - it should say `1.10.1`.

**Comment by Sergio-Mira** [comment] 2018-09-14 09:48
Hi @samstokes will try and give it a go in our staging environment next week and report here, thanks!

**Comment by samstokes** [comment] 2018-10-04 19:57
Hey @Sergio-Mira, just wondering if you'd had a chance to test whether the new version of libhoney resolves the issue you're seeing?

**Comment by samstokes** [comment] 2018-10-04 20:11
Closing this for now since there's reason to believe it's been resolved, and we can't reproduce it locally. Please reopen if you're still having this issue though!

**Closed by samstokes** 2018-10-04 20:11 UTC

**Comment by Sergio-Mira** [comment] 2018-11-20 11:04
Latest version of the libs fixed our issues, thanks!

**Comment by martin308** [comment] 2018-11-20 15:59
Great, thanks for letting us know @Sergio-Mira! 🎉
