### ISSUE TITLE
Can't get it working using Puma

### ISSUE THREAD

**Issue by mattjstar** [honeycombio/honeycomb-rails#29] opened 2018-09-11 13:57 UTC
Saw this issue here: https://github.com/honeycombio/honeycomb-rails/issues/22

Having a similar issue with Puma. To clarify the database dataset is sending over fine, it's the application dataset that isn't getting anything.

Using Heroku, with the following procfile:
```
web: eval bin/start-stunnel bundle exec puma -C config/puma.rb
```

Gem version: 0.8

Has anyone else run into this issue?

**Comment by mattjstar** [comment] 2018-09-11 14:04
Don't know if this is helpful, but here's what I get in the logs when I restart my heroku app:

```
2018-09-11T14:02:49.380589+00:00 app[web.1]: [10] ! #<Thread:0x00000000015f8e20@/app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:297 sleep> - /app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:299:in `sleep'
2018-09-11T14:02:49.380659+00:00 app[web.1]: [10] ! #<Thread:0x00000000031a4d18@/app/vendor/bundle/ruby/2.4.0/gems/libhoney-1.10.1/lib/libhoney/transmission.rb:127 sleep_forever> - /app/vendor/bundle/ruby/2.4.0/gems/libhoney-1.10.1/lib/libhoney/transmission.rb:55:in `pop'
2018-09-11T14:02:49.380767+00:00 app[web.1]: [10] ! #<Thread:0x000000000303eb40@/app/vendor/bundle/ruby/2.4.0/gems/libhoney-1.10.1/lib/libhoney/transmission.rb:127 sleep_forever> - /app/vendor/bundle/ruby/2.4.0/gems/libhoney-1.10.1/lib/libhoney/transmission.rb:55:in `pop'
2018-09-11T14:02:49.380818+00:00 app[web.1]: [10] ! #<Thread:0x000000000303dfd8@/app/vendor/bundle/ruby/2.4.0/gems/libhoney-1.10.1/lib/libhoney/transmission.rb:127 sleep_forever> - /app/vendor/bundle/ruby/2.4.0/gems/libhoney-1.10.1/lib/libhoney/transmission.rb:55:in `pop'
2018-09-11T14:02:49.380870+00:00 app[web.1]: [10] ! #<Thread:0x000000000303d510@/app/vendor/bundle/ruby/2.4.0/gems/libhoney-1.10.1/lib/libhoney/transmission.rb:127 sleep_forever> - /app/vendor/bundle/ruby/2.4.0/gems/libhoney-1.10.1/lib/libhoney/transmission.rb:55:in `pop'
2018-09-11T14:02:49.380711+00:00 app[web.1]: [10] ! #<Thread:0x00000000031a2630@/app/vendor/bundle/ruby/2.4.0/gems/libhoney-1.10.1/lib/libhoney/transmission.rb:127 sleep_forever> - /app/vendor/bundle/ruby/2.4.0/gems/libhoney-1.10.1/lib/libhoney/transmission.rb:55:in `pop'
2018-09-11T14:02:49.380919+00:00 app[web.1]: [10] ! #<Thread:0x000000000303ca70@/app/vendor/bundle/ruby/2.4.0/gems/libhoney-1.10.1/lib/libhoney/transmission.rb:127 sleep_forever> - /app/vendor/bundle/ruby/2.4.0/gems/libhoney-1.10.1/lib/libhoney/transmission.rb:55:in `pop'
2018-09-11T14:02:49.381060+00:00 app[web.1]: [10] ! #<Thread:0x000000000300ee68@/app/vendor/bundle/ruby/2.4.0/gems/libhoney-1.10.1/lib/libhoney/transmission.rb:127 sleep_forever> - /app/vendor/bundle/ruby/2.4.0/gems/libhoney-1.10.1/lib/libhoney/transmission.rb:55:in `pop'
2018-09-11T14:02:49.381004+00:00 app[web.1]: [10] ! #<Thread:0x0000000003018be8@/app/vendor/bundle/ruby/2.4.0/gems/libhoney-1.10.1/lib/libhoney/transmission.rb:127 sleep_forever> - /app/vendor/bundle/ruby/2.4.0/gems/libhoney-1.10.1/lib/libhoney/transmission.rb:55:in `pop'
2018-09-11T14:02:49.387931+00:00 app[web.1]: [10] - Worker 0 (pid: 24) booted, phase: 0
2018-09-11T14:02:49.380969+00:00 app[web.1]: [10] ! #<Thread:0x0000000003027968@/app/vendor/bundle/ruby/2.4.0/gems/libhoney-1.10.1/lib/libhoney/transmission.rb:127 sleep_forever> - /app/vendor/bundle/ruby/2.4.0/gems/libhoney-1.10.1/lib/libhoney/transmission.rb:55:in `pop'
2018-09-11T14:02:49.381104+00:00 app[web.1]: [10] ! #<Thread:0x000000000300e120@/app/vendor/bundle/ruby/2.4.0/gems/libhoney-1.10.1/lib/libhoney/transmission.rb:127 sleep_forever> - /app/vendor/bundle/ruby/2.4.0/gems/libhoney-1.10.1/lib/libhoney/transmission.rb:55:in `pop'
2018-09-11T14:02:49.381214+00:00 app[web.1]: [10] Use Ctrl-C to stop
```

**Comment by mattjstar** [comment] 2018-09-13 12:03
Just checked and it looks like it's now working. Did something change?

**Comment by samstokes** [comment] 2018-09-13 17:16
Hi @mattjstar, sorry for not responding sooner here. I've been trying to reproduce this issue but with no luck.

Thanks for letting us know it's working now! Is there any chance you have the `Gemfile.lock` from the time when it didn't work, that you could compare with your current `Gemfile.lock`? We recently put out a new release of libhoney (our SDK) that improved error handling that might have mitigated this issue.

I'd still like to get to the bottom of it though. Any chance you could share your `config/puma.rb` (or the values of `workers`, `preload_app!` and whether you're doing anything in `on_worker_boot`)?

**Comment by mattjstar** [comment] 2018-09-13 18:13
That's the weird thing, I didn't update the Gemfile from when it didn't work to when it works now!

Here's the Gemfile.lock:
```
GEM
  remote: https://rubygems.org/
  specs:
    actioncable (5.2.0)
      actionpack (= 5.2.0)
      nio4r (~> 2.0)
      websocket-driver (>= 0.6.1)
    actionmailer (5.2.0)
      actionpack (= 5.2.0)
      actionview (= 5.2.0)
      activejob (= 5.2.0)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 2.0)
    actionpack (5.2.0)
      actionview (= 5.2.0)
      activesupport (= 5.2.0)
      rack (~> 2.0)
      rack-test (>= 0.6.3)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    actionview (5.2.0)
      activesupport (= 5.2.0)
      builder (~> 3.1)
      erubi (~> 1.4)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.0.3)
    active_model_serializers (0.10.7)
      actionpack (>= 4.1, < 6)
      activemodel (>= 4.1, < 6)
      case_transform (>= 0.2)
      jsonapi-renderer (>= 0.1.1.beta1, < 0.3)
    activeadmin (1.3.0)
      arbre (>= 1.1.1)
      coffee-rails
      formtastic (~> 3.1)
      formtastic_i18n
      inherited_resources (>= 1.7.0)
      jquery-rails (>= 4.2.0)
      kaminari (>= 0.15)
      railties (>= 4.2, < 5.3)
      ransack (~> 1.3)
      sass (~> 3.1)
      sprockets (< 4.1)
    activejob (5.2.0)
      activesupport (= 5.2.0)
      globalid (>= 0.3.6)
    activemodel (5.2.0)
      activesupport (= 5.2.0)
    activerecord (5.2.0)
      activemodel (= 5.2.0)
      activesupport (= 5.2.0)
      arel (>= 9.0)
    activestorage (5.2.0)
      actionpack (= 5.2.0)
      activerecord (= 5.2.0)
      marcel (~> 0.3.1)
    activesupport (5.2.0)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 0.7, < 2)
      minitest (~> 5.1)
      tzinfo (~> 1.1)
    addressable (2.5.2)
      public_suffix (>= 2.0.2, < 4.0)
    annotate (2.7.2)
      activerecord (>= 3.2, < 6.0)
      rake (>= 10.4, < 13.0)
    arbre (1.1.1)
      activesupport (>= 3.0.0)
    arel (9.0.0)
    ast (2.3.0)
    awesome_print (1.8.0)
    aws-partitions (1.48.0)
    aws-sdk-core (3.11.0)
      aws-partitions (~> 1.0)
      aws-sigv4 (~> 1.0)
      jmespath (~> 1.0)
    aws-sdk-kms (1.3.0)
      aws-sdk-core (~> 3)
      aws-sigv4 (~> 1.0)
    aws-sdk-s3 (1.8.0)
      aws-sdk-core (~> 3)
      aws-sdk-kms (~> 1)
      aws-sigv4 (~> 1.0)
    aws-sigv4 (1.0.2)
    bootsnap (1.3.1)
      msgpack (~> 1.0)
    builder (3.2.3)
    byebug (9.1.0)
    case_transform (0.2)
      activesupport
    coffee-rails (4.2.2)
      coffee-script (>= 2.2.0)
      railties (>= 4.0.0)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.12.2)
    concurrent-ruby (1.0.5)
    crass (1.0.4)
    diff-lcs (1.3)
    domain_name (0.5.20180417)
      unf (>= 0.0.5, < 1.0.0)
    dotenv (2.5.0)
    dotenv-rails (2.5.0)
      dotenv (= 2.5.0)
      railties (>= 3.2, < 6.0)
    erubi (1.7.1)
    execjs (2.7.0)
    factory_bot (4.8.2)
      activesupport (>= 3.0.0)
    faraday (0.10.0)
      multipart-post (>= 1.2, < 3)
    ffi (1.9.25)
    formtastic (3.1.5)
      actionpack (>= 3.2.13)
    formtastic_i18n (0.6.0)
    globalid (0.4.1)
      activesupport (>= 4.2.0)
    has_scope (0.7.2)
      actionpack (>= 4.1)
      activesupport (>= 4.1)
    hashie (3.5.7)
    honeycomb-rails (0.8.0)
      libhoney (>= 1.8.1)
      rails (>= 3.0.0)
    http (3.3.0)
      addressable (~> 2.3)
      http-cookie (~> 1.0)
      http-form_data (~> 2.0)
      http_parser.rb (~> 0.6.0)
    http-cookie (1.0.3)
      domain_name (~> 0.5)
    http-form_data (2.1.1)
    http_parser.rb (0.6.0)
    i18n (1.0.1)
      concurrent-ruby (~> 1.0)
    inherited_resources (1.8.0)
      actionpack (>= 4.2, <= 5.2)
      has_scope (~> 0.6)
      railties (>= 4.2, <= 5.2)
      responders
    jmespath (1.3.1)
    jquery-rails (4.3.3)
      rails-dom-testing (>= 1, < 3)
      railties (>= 4.2.0)
      thor (>= 0.14, < 2.0)
    jsonapi-renderer (0.2.0)
    jwt (1.5.6)
    kaminari (1.1.1)
      activesupport (>= 4.1.0)
      kaminari-actionview (= 1.1.1)
      kaminari-activerecord (= 1.1.1)
      kaminari-core (= 1.1.1)
    kaminari-actionview (1.1.1)
      actionview
      kaminari-core (= 1.1.1)
    kaminari-activerecord (1.1.1)
      activerecord
      kaminari-core (= 1.1.1)
    kaminari-core (1.1.1)
    libhoney (1.10.1)
      http (>= 2.0, < 4.0)
    listen (3.1.5)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
      ruby_dep (~> 1.2)
    loofah (2.2.2)
      crass (~> 1.0.2)
      nokogiri (>= 1.5.9)
    mail (2.7.0)
      mini_mime (>= 0.1.1)
    marcel (0.3.2)
      mimemagic (~> 0.3.2)
    method_source (0.9.0)
    mimemagic (0.3.2)
    mini_mime (1.0.0)
    mini_portile2 (2.3.0)
    minitest (5.11.3)
    msgpack (1.2.4)
    multi_json (1.12.2)
    multi_xml (0.6.0)
    multipart-post (2.0.0)
    nio4r (2.3.1)
    nokogiri (1.8.4)
      mini_portile2 (~> 2.3.0)
    oauth2 (1.4.0)
      faraday (>= 0.8, < 0.13)
      jwt (~> 1.0)
      multi_json (~> 1.3)
      multi_xml (~> 0.5)
      rack (>= 1.2, < 3)
    omniauth (1.6.1)
      hashie (>= 3.4.6, < 3.6.0)
      rack (>= 1.6.2, < 3)
    omniauth-auth0 (2.0.0)
      omniauth-oauth2 (~> 1.4)
    omniauth-oauth2 (1.5.0)
      oauth2 (~> 1.1)
      omniauth (~> 1.2)
    parallel (1.12.0)
    paranoia (2.4.1)
      activerecord (>= 4.0, < 5.3)
    parser (2.4.0.2)
      ast (~> 2.3)
    pg (0.21.0)
    polyamorous (1.3.3)
      activerecord (>= 3.0)
    powerpack (0.1.1)
    public_suffix (3.0.3)
    puma (3.11.0)
    pundit (1.1.0)
      activesupport (>= 3.0.0)
    rack (2.0.5)
    rack-cors (1.0.2)
    rack-test (1.1.0)
      rack (>= 1.0, < 3)
    rails (5.2.0)
      actioncable (= 5.2.0)
      actionmailer (= 5.2.0)
      actionpack (= 5.2.0)
      actionview (= 5.2.0)
      activejob (= 5.2.0)
      activemodel (= 5.2.0)
      activerecord (= 5.2.0)
      activestorage (= 5.2.0)
      activesupport (= 5.2.0)
      bundler (>= 1.3.0)
      railties (= 5.2.0)
      sprockets-rails (>= 2.0.0)
    rails-dom-testing (2.0.3)
      activesupport (>= 4.2.0)
      nokogiri (>= 1.6)
    rails-html-sanitizer (1.0.4)
      loofah (~> 2.2, >= 2.2.2)
    railties (5.2.0)
      actionpack (= 5.2.0)
      activesupport (= 5.2.0)
      method_source
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    rainbow (2.2.2)
      rake
    rake (12.3.1)
    ransack (1.8.8)
      actionpack (>= 3.0)
      activerecord (>= 3.0)
      activesupport (>= 3.0)
      i18n
      polyamorous (~> 1.3.2)
    rb-fsevent (0.10.3)
    rb-inotify (0.9.10)
      ffi (>= 0.5.0, < 2)
    redis (4.0.1)
    responders (2.4.0)
      actionpack (>= 4.2.0, < 5.3)
      railties (>= 4.2.0, < 5.3)
    rollbar (2.15.5)
      multi_json
    rspec-core (3.7.1)
      rspec-support (~> 3.7.0)
    rspec-expectations (3.7.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.7.0)
    rspec-mocks (3.7.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.7.0)
    rspec-rails (3.7.2)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      railties (>= 3.0)
      rspec-core (~> 3.7.0)
      rspec-expectations (~> 3.7.0)
      rspec-mocks (~> 3.7.0)
      rspec-support (~> 3.7.0)
    rspec-support (3.7.1)
    rubocop (0.51.0)
      parallel (~> 1.10)
      parser (>= 2.3.3.1, < 3.0)
      powerpack (~> 0.1)
      rainbow (>= 2.2.2, < 3.0)
      ruby-progressbar (~> 1.7)
      unicode-display_width (~> 1.0, >= 1.0.1)
    ruby-progressbar (1.9.0)
    ruby_dep (1.5.0)
    sass (3.5.7)
      sass-listen (~> 4.0.0)
    sass-listen (4.0.0)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
    spring (2.0.2)
      activesupport (>= 4.2)
    spring-watcher-listen (2.0.1)
      listen (>= 2.7, < 4.0)
      spring (>= 1.2, < 3.0)
    sprockets (3.7.2)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (3.2.1)
      actionpack (>= 4.0)
      activesupport (>= 4.0)
      sprockets (>= 3.0.0)
    thor (0.20.0)
    thread_safe (0.3.6)
    tzinfo (1.2.5)
      thread_safe (~> 0.1)
    unf (0.1.4)
      unf_ext
    unf_ext (0.0.7.5)
    unicode-display_width (1.3.0)
    websocket-driver (0.7.0)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.3)

PLATFORMS
  ruby

DEPENDENCIES
  active_model_serializers (~> 0.10.7)
  activeadmin (~> 1.3.0)
  annotate
  awesome_print
  aws-sdk-s3 (~> 1)
  bootsnap (>= 1.1.0)
  byebug
  dotenv-rails (~> 2.5)
  factory_bot (~> 4.0)
  faraday (= 0.10)
  honeycomb-rails (~> 0.8)
  jwt (~> 1.5)
  listen (>= 3.0.5, < 3.2)
  omniauth (~> 1.6.1)
  omniauth-auth0 (~> 2.0.0)
  paranoia (~> 2.2)
  pg (~> 0.18)
  puma (~> 3.7)
  pundit (~> 1.1)
  rack-cors
  rails (~> 5.2.0)
  redis (~> 4.0)
  rollbar (~> 2.15)
  rspec-rails (~> 3.7.2)
  rubocop (~> 0.51.0)
  spring
  spring-watcher-listen (~> 2.0.0)
  tzinfo-data

RUBY VERSION
   ruby 2.4.2p198

BUNDLED WITH
   1.16.1
```

**Comment by mattjstar** [comment] 2018-09-13 18:15
Pretty Standard Puma config, although I am using stunnel (cause we use redis, following heroku's docs [here](https://devcenter.heroku.com/articles/securing-heroku-redis))

Procfile command:
```
web: bin/start-stunnel bundle exec puma -C config/puma.rb
```

Config:
```
# BASED ON https://devcenter.heroku.com/articles/deploying-rails-applications-with-the-puma-web-server

# Puma can serve each request in a thread from an internal thread pool.
# The `threads` method setting takes two numbers: a minimum and maximum.
# Any libraries that use thread pools should be configured to match
# the maximum value specified for Puma. Default is set to 5 threads for minimum
# and maximum; this matches the default thread size of Active Record.
#
threads_count = ENV.fetch("RAILS_MAX_THREADS") { 5 }
threads threads_count, threads_count

# Specifies the `port` that Puma will listen on to receive requests; default is 3001.
#
rackup      DefaultRackup
port        ENV['PORT']     || 3001

# Specifies the `environment` that Puma will run in.
#
environment ENV.fetch("RAILS_ENV") { "development" }

# Specifies the number of `workers` to boot in clustered mode.
# Workers are forked webserver processes. If using threads and workers together
# the concurrency of the application would be max `threads` * `workers`.
# Workers do not work on JRuby or Windows (both of which do not support
# processes).
#
workers ENV.fetch("WEB_CONCURRENCY") { 2 }

# Use the `preload_app!` method when specifying a `workers` number.
# This directive tells Puma to first boot the application and load code
# before forking the application. This takes advantage of Copy On Write
# process behavior so workers use less memory. If you use this option
# you need to make sure to reconnect any threads in the `on_worker_boot`
# block.
#
preload_app!

# If you are preloading your application and using Active Record, it's
# recommended that you close any connections to the database before workers
# are forked to prevent connection leakage.
#
# before_fork do
#   ActiveRecord::Base.connection_pool.disconnect! if defined?(ActiveRecord)
# end

# The code in the `on_worker_boot` will be called if you are using
# clustered mode by specifying a number of `workers`. After each worker
# process is booted, this block will be run. If you are using the `preload_app!`
# option, you will want to use this block to reconnect to any threads
# or connections that may have been created at application boot, as Ruby
# cannot share connections between processes.
#
on_worker_boot do
  # Worker specific setup for Rails 4.1+
  # See: https://devcenter.heroku.com/articles/deploying-rails-applications-with-the-puma-web-server#on-worker-boot
  ActiveRecord::Base.establish_connection
end
#

# Allow puma to be restarted by `rails restart` command.
plugin :tmp_restart

```

**Comment by samstokes** [comment] 2018-10-04 20:11
Closing this for now since it's been resolved, and we can't reproduce it locally. Please reopen if you're still having this issue though!

**Closed by samstokes** 2018-10-04 20:11 UTC
